# Generated by Django 5.1.2 on 2024-10-09 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("UserManagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the sender", max_length=255),
                ),
                (
                    "username",
                    models.EmailField(
                        help_text="Email address of the sender", max_length=254
                    ),
                ),
                (
                    "password",
                    models.CharField(help_text="Encrypted password", max_length=255),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.PositiveIntegerField()),
                ("use_tls", models.BooleanField(default=False)),
                ("use_ssl", models.BooleanField(default=False)),
                ("system_default", models.BooleanField(default=False)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="UserManagement.user",
                    ),
                ),
            ],
        ),
    ]
