version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 src.wsgi:application
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env  # Ensure your environment variables are here
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A src worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - ./env/.env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword

volumes:
  postgres_data:
  media:
