# Generated by Django 5.0.2 on 2024-11-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtp',
            name='is_deleted',
        ),
    ]
