# Generated by Django 5.1.2 on 2024-10-24 11:53

import django.db.models.deletion
import src.apps.common.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "InActive")],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("applicant_id", models.UUIDField()),
                ("deployment_url", models.URLField()),
                ("project_github_url", models.URLField()),
                ("video_url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobApplicant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "InActive")],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "total_yoe",
                    models.CharField(
                        help_text="Total years of experience", max_length=10
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        help_text="Comma-separated skills", max_length=255
                    ),
                ),
                ("linkedin", models.URLField()),
                (
                    "resume",
                    models.FileField(upload_to=src.apps.common.utils.get_upload_folder),
                ),
                ("assignment_sent", models.BooleanField(default=False)),
                ("assignment_submitted", models.BooleanField(default=False)),
                ("offer_letter_sent", models.BooleanField(default=False)),
                ("offer_letter_signed", models.BooleanField(default=False)),
                (
                    "submitted_offer_letter",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("applicant_accepted", models.BooleanField(default=False)),
                (
                    "job_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.jobtemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobApplicantExtraField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "InActive")],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.JSONField()),
                (
                    "job_applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicant.jobapplicant",
                    ),
                ),
                (
                    "template_extra_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.templateextrafield",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
