# Generated by Django 5.0.9 on 2024-10-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplicant',
            old_name='offer_letter_submitted',
            new_name='offer_letter_signed',
        ),
        migrations.RenameField(
            model_name='jobapplicant',
            old_name='signed_offer_letter',
            new_name='submitted_offer_letter',
        ),
    ]
