# Generated by Django 5.0.2 on 2024-11-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_jobapplicant_offer_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicantextrafield',
            name='value',
            field=models.TextField(null=True),
        ),
    ]
