# Generated by Django 5.0.2 on 2024-11-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_jobapplicantextrafield_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='jobapplicant',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='jobapplicantextrafield',
            name='is_deleted',
        ),
    ]
