# Generated by Django 5.0.2 on 2024-11-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_remove_assignmentsubmission_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
