# Generated by Django 5.0.2 on 2024-11-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0010_assignmentsubmission_assignment_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplicantextrafield',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
