# Generated by Django 5.0.2 on 2024-11-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0011_assignmentsubmission_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='application_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
