# Generated by Django 5.0.2 on 2024-11-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0012_jobapplicant_application_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='applicant_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
