# Generated by Django 5.0.2 on 2024-10-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobtemplate_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='country_location',
            field=models.CharField(default='India', max_length=255),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='work_type',
            field=models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full time', max_length=255),
        ),
        migrations.AlterField(
            model_name='templateextrafield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('select', 'Select'), ('rich text', 'Rich Text')], default='text', max_length=50),
        ),
    ]
