# Generated by Django 5.0.2 on 2024-10-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobtemplate_country_location_jobtemplate_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
