# Generated by Django 5.0.2 on 2024-10-30 07:12

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_jobtemplate_country_location_jobtemplate_experience_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offertemplate",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="offertemplate",
            name="created_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="offertemplate",
            name="html_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offertemplate",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offertemplate",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="offertemplate",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="content"
            ),
        ),
        migrations.AlterField(
            model_name="offertemplate",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
