# Generated by Django 5.0.2 on 2024-10-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_offertemplate_author_offertemplate_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
