# Generated by Django 5.0.2 on 2024-11-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_jobtemplate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicanttemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='jobassignmenttemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='jobtemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='offertemplate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='templateextrafield',
            name='is_deleted',
        ),
    ]
