# Generated by Django 5.0.2 on 2024-11-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_jobapplicanttemplate_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassignmenttemplate',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='offertemplate',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
