# Generated by Django 5.0.2 on 2024-11-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobassignmenttemplate_objective'),
        ('job', '0008_alter_jobassignmenttemplate_content_and_more'),
    ]

    operations = [
    ]
