# Generated by Django 5.0.2 on 2024-11-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_merge_20241107_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicanttemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobassignmenttemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offertemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='templateextrafield',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
