# Generated by Django 5.0.2 on 2024-11-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_jobapplicanttemplate_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offertemplate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='offertemplate',
            name='created_date',
        ),
    ]
