# Generated by Django 5.0.2 on 2024-11-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_jobtemplate_joining_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offertemplate',
            name='html_content',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
