# Generated by Django 5.0.2 on 2024-11-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_offertemplate_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='payable',
            field=models.CharField(blank=True, default='monthly', max_length=255, null=True),
        ),
    ]
