# Generated by Django 5.0.2 on 2024-10-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
