# Generated by Django 5.0.9 on 2024-10-10 03:14

import src.apps.common.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='active', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=src.apps.common.utils.get_upload_folder)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('linkedin', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
