# Generated by Django 5.0.2 on 2024-11-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_deleted',
        ),
    ]
