# Generated by Django 5.0.9 on 2024-10-11 05:38

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='work_type',
            field=models.CharField(choices=[('full_time', 'Full_Time'), ('part_time', 'Part_Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobassignmenttemplate',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='offertemplate',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
