# Generated by Django 5.0.9 on 2024-10-11 05:40

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_jobtemplate_work_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassignmenttemplate',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='offertemplate',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='content'),
        ),
    ]
