# Generated by Django 5.0.9 on 2024-10-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_alter_jobassignmenttemplate_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
