# Generated by Django 5.0.9 on 2024-10-16 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_alter_jobtemplate_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], default='active', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('applicant_id', models.UUIDField()),
                ('deployment_url', models.URLField()),
                ('project_github_url', models.URLField()),
                ('video_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='jobtemplate',
            old_name='position',
            new_name='department',
        ),
    ]
