# Generated by Django 5.1.2 on 2024-10-09 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("JobManagement", "0001_initial"),
        ("TemplateManagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplicant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "total_yoe",
                    models.CharField(
                        help_text="Total years of experience", max_length=10
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        help_text="Comma-separated skills", max_length=255
                    ),
                ),
                ("linkedin", models.URLField()),
                ("resume", models.FileField(upload_to="resumes/")),
                (
                    "job_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="JobManagement.jobtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApplicantExtraField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.JSONField()),
                (
                    "job_applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ApplicantManagement.jobapplicant",
                    ),
                ),
                (
                    "template_extra_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="TemplateManagement.templateextrafield",
                    ),
                ),
            ],
        ),
    ]
